{% set name = "dash" %}
{% set version = "2.18.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/dash-{{ version }}.tar.gz
  sha256: 20e8404f73d0fe88ce2eae33c25bbc513cbe52f30d23a401fa5f24dbb44296c8

build:
  entry_points:
    - dash-generate-components = dash.development.component_generator:cli
    - renderer = dash.development.build_process:renderer
    - dash-update-components = dash.development.update_components:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - flask >=1.0.4,<3.1
    - werkzeug <3.1
    - plotly >=5.0.0
    - dash-html-components ==2.0.0
    - dash-core-components ==2.0.0
    - dash-table ==5.0.0
    - importlib-metadata
    - typing_extensions >=4.1.1
    - requests
    - retrying
    - nest-asyncio
    - setuptools

test:
  imports:
    - dash
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources
    - dash.dcc
    - dash.html
    - dash.dash_table
    - dash.testing
  commands:
    - pip check
    - dash-generate-components --help
    - renderer --help
    - dash-update-components --help
  requires:
    - python {{ python_min }}
    - pip
    - coloredlogs >=15.0.1
    - fire >=0.4.0
    - pyyaml >=5.4.1

about:
  home: https://plotly.com/dash
  summary: A Python framework for building reactive web-apps. Developed by Plotly.
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bandersen23
    - moorepants
