{% set name = "dash" %}
{% set version = "1.0.1" %}
{% set sha256 = "2d287101c71280d06cf4dbd102feef1889a9172d4b0065b7345d49ce230c1be5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - pyyaml >=5.1.1
    - flask >=1.0.2
    - flask-compress
    - plotly
    - dash-renderer ==1.0.0
    - dash-core-components ==1.0.0
    - dash-html-components ==1.0.0
    - dash-table ==4.0.1
    
test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A Python framework for building reactive web-apps.'

extra:
  recipe-maintainers:
    - moorepants
