{% set name = "dash" %}
{% set version = "2.4.0" %}
{% set sha256 = "7450d3a55b2e6d378216dcdca04b050b68d834c1d955fc0c6d9823f0e4290598" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - setuptools
    - pip
  run:
    - python >=3.6
    - setuptools
    - flask >=1.0.4
    - flask-compress
    - plotly >=5.0.0
  run_constrained:
    - dash-html-components >=2.0.0
    - dash-core-components >=2.0.0
    - dash_table >=5.0.0

test:
  requires:
    - pytest
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources
    - dash.dcc
    - dash.html
    - dash.dash_table
  commands:
    - pytest test_not_found.py
    - conda install -c conda-forge dash-html-components dash-core-components dash-table -y
    - pytest test_warnings.py
  files:
    - test_not_found.py
    - test_warnings.py

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  doc_url: https://dash.plotly.com
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.

extra:
  recipe-maintainers:
    - bandersen23
    - moorepants
