{% set name = "dash" %}
{% set version = "1.18.1" %}
{% set sha256 = "f4f82d63db13c19e15c01fc865fb35f32cb861dab36c372ccd79c96ee699a882" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python ==2.7.*|>=3.3
    - setuptools
    - pip
  run:
    - python ==2.7.*|>=3.3
    - pyyaml >=5.1.1
    - flask >=1.0.2
    - flask-compress
    - plotly
    - dash-renderer ==1.8.3
    - dash-core-components ==1.14.0
    - dash-html-components ==1.1.1
    - dash-table ==4.11.0
    - future

test:
  imports:
    - dash.dash
    - dash.dependencies
    - dash.exceptions
    - dash.resources

about:
  home: https://plot.ly/dash
  dev_url: https://github.com/plotly/dash
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A Python framework for building reactive web-apps.

extra:
  recipe-maintainers:
    - moorepants
    - raybellwaves
